=== rogerchina/KnowledgeBase/codelabs-demo/src/main/java/com/debuglife/codelabs/jaxb/g4m-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>Define the g4m workflow configuration</xs:documentation>
	</xs:annotation>
	
	<xs:element name="g4m-configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="routes" type="routes"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="routes">
		<xs:all>
			<xs:element name="globalExceptionStrategy" type="globalExceptionStrategy" minOccurs="0" maxOccurs="1"/>
			<xs:element name="route" type="route" minOccurs="0" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="globalExceptionStrategy">
		<xs:annotation>
			<xs:documentation>Defines one global exception handling strategy</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="redeliveryDelay" type="xs:int" minOccurs="0" maxOccurs="1" default="2000"/>
			<xs:element name="maximumRedeliveries" type="xs:int" minOccurs="0" maxOccurs="1" default="5"/>
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="route">
		<xs:annotation>
			<xs:documentation>Defines some common used configuration for route</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="from" type="from" minOccurs="1"/>
			<xs:element name="script" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="to" type="to" minOccurs="1"/>
		</xs:all>
		<xs:attribute name="routeId" type="xs:string" use="required"/>
		<xs:attribute name="autoStartup" type="xs:string" default="false"/>
	</xs:complexType>
	
	<xs:complexType name="from">
		<xs:annotation>
			<xs:documentation>Defines route's inbound configuration</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="ipAddress" type="xs:string"/>
			<xs:element name="port">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="65535"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="to">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="transportType" type="xs:string" />
			<xs:element name="ipAddress" type="xs:string"/>
			<xs:element name="port">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="65535"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== rogerchina/KnowledgeBase/codelabs-demo/src/main/java/com/debuglife/codelabs/jaxb/g4m-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<g4m-configuration xsi:noNamespaceSchemaLocation="g4m-configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<routes>
		<!-- The global strategy when exception occurred. -->
		<globalExceptionStrategy>
			<redeliveryDelay>1</redeliveryDelay>
			<maximumRedeliveries>1</maximumRedeliveries>
		</globalExceptionStrategy>
		
		<!-- Route definition -->
		<route routeId="PMN-RIS" autoStartup=false>
			<from>
				<ipAddress>x.x.x.x</ipAddress>
				<port>3333</port>
			</from>
			<script>/home/roger/script/ADT2ORU.js</script>
			<to>
				<name>RIS-A</name>
				<!-- HTTP,FTP,TCP,FILE,RELABIT -->
				<transportType>FTP</transportType>
				<ipAddress>x.x.x.x</ipAddress>
				<port>1111</port>
				<!-- The route-specific exception strategy, if no set, -->
				<!-- one default strategy will be used -->
				<!-- 
				<excepitonStrategy>
					<redeliveryDelay></redeliveryDelay>
					<maximumRedeliveries></maximumRedeliveries>
					<timeout></timeout>
				</excepitonStrategy>
				 -->
			</to>
		</route>
	</routes>
</g4m-configuration>
